### ISSUE TITLE
add these

### ISSUE THREAD

**Issue by yasmasdas** [Wildbrick142/V-Tunable-Names#1]
0x3738eaa0 gb_belly_event_multiplier_rp (CONFIRMED MATCH)

0xb61e2da1 gb_belly_event_multiplier_cash (CONFIRMED MATCH)

0x26afc1fa gb_assault_event_multiplier_cash (CONFIRMED MATCH)

0x2922c94e gb_protectionracket_rp_reward_winner (CONFIRMED MATCH)

0x7485ef76 gb_protectionracket_delivery_distance (CONFIRMED MATCH)

0x1af948d8 gb_protectionracket_event_multiplier_rp (CONFIRMED MATCH)

0x5ea0f3dc gb_pointtopoint_event_multiplier_rp (CONFIRMED MATCH)

0x91648975 gb_pointtopoint_rp_reward_winner (CONFIRMED MATCH)

0x4fccd9cd gb_mostwanted_event_multiplier_rp (CONFIRMED MATCH)

0xc02889e8 gb_mostwanted_rp_reward_winner (CONFIRMED MATCH)

0x864736ad gb_finders_keepers_disable_trackify (CONFIRMED MATCH)

0x9d15e7a6 gb_finders_keepers_rp_reward_winner (CONFIRMED MATCH)

0xff82137b gb_carjacking_rp_reward_winner (CONFIRMED MATCH)

0x08d43380 gb_yachtattack_event_multiplier_rp (CONFIRMED MATCH)

0x8495205b gb_yachtattack_event_multiplier_cash (CONFIRMED MATCH)

0xf8fe74a8 gb_carjacking_car_value_cap (CONFIRMED MATCH)

0x1a2f856e gb_assault_event_multiplier_rp (CONFIRMED MATCH)

0xf8a48655 gb_finders_keepers_event_multiplier_rp (CONFIRMED MATCH)

0x118de6b1 gb_huntboss_event_multiplier_rp (CONFIRMED MATCH)

0x6d5c9385 gb_huntboss_event_multiplier_cash (CONFIRMED MATCH)

0x07448eec gb_sightseer_event_multiplier_cash (CONFIRMED MATCH)

**Comment by yasmasdas** [comment]
you can probably also get more event_multiplier tuneables I didn't use a full vip work list

**Comment by yasmasdas** [comment]
also are you sure these are correct

joaat("GB_BELLY_WANTED_COUNTRY")
joaat("GB_BELLY_WANTED_CITY")

yes they have to do witrh wanted levels but how are they related to country / city

**Comment by Wildbrick142** [comment]
added. thanks!
