### ISSUE TITLE
#10 continuation kinda

### ISSUE THREAD

**Issue by yasmasdas** [Wildbrick142/V-Tunable-Names#12]
#10 continuation kinda

0xfdd977b4 h2_medal_time_start_value
0x3f2e13da h2_medal_time_multiplier
0x049609ae h2_medal_kills_multiplier
0xcb6a7b38 h2_medal_max_kills
0xd161cc11 h2_medal_ambient_cop_kills_multiplier
0xd9be5362 h2_medal_max_ambient_cop_kills
0x3888c7fd h2_medal_head_shot_multiplier
0x18f9665f h2_medal_max_headshots
0x90a5679c h2_medal_safe_drive_multiplier
0xc1973141 h2_medal_safe_drive_time_multiplier
0xb78cf711 h2_medal_accuracy_multiplier
0xd1a6b517 h2_medal_civillian_kills_multiplier
0x2804218f h2_medal_max_civillian_kills
0x255ac6a0 h2_medal_health_score_start_value
0x4994f67a h2_medal_health_score_multiplier_0
0xe7c4b2db h2_medal_health_score_multiplier_1
0x580e248c h2_medal_hack_score_start_value
0xdc13b9a7 h2_medal_hack_score_multiplier
0x53d7c1ec h2_medal_max_hacks
0x0374d7c0 h2_medal_max_wanted_level
0x2de2926d h2_medal_wanted_level_multiplier
0xe046b5c9 h2_medal_wanted_level_time_multiplier
0x5a7a8997 h2_medal_objective_max_team_players
0xa1f44103 h2_medal_objective_multiplier

**Comment by Wildbrick142** [comment]
names have been (finally) added. thanks
