### ISSUE TITLE
Probably a typo

### ISSUE THREAD

**Issue by PLTytus** [Wildbrick142/V-Tunable-Names#16]
On the list there is: `DISCOUNT_FEMALE_GLASSES_BROWN_MARBLE_LÉZARD_CLASSIC`
I believe it should be: `DISCOUNT_FEMALE_GLASSES_BROWN_MARBLE_LÉZARD_CLASSICS`
With `S` on the end.

**Comment by Wildbrick142** [comment]
confirmed a typo. thanks for pointing it out, it's been fixed
