### ISSUE TITLE
add these

### ISSUE THREAD

**Issue by yasmasdas** [Wildbrick142/V-Tunable-Names#2]
0xe86e19e4 turn_on_kill_quota (CONFIRMED MATCH)
0x7a219cac exec1_pa_pegasus_monster (CONFIRMED MATCH)
0x2c370ffb exec1_pa_pegasus_cargobob (CONFIRMED MATCH)
0xaa368bc3 exec1_pa_pegasus_swift (CONFIRMED MATCH)
0x9517b17c exec1_pa_pegasus_maverick (CONFIRMED MATCH)
0x4897bda5 exec1_pa_pegasus_valkyrie (CONFIRMED MATCH)
0xc4a7d8be exec1_pa_pegasus_stretch (CONFIRMED MATCH)
0x1b07d821 exec1_pa_pegasus_volatus (CONFIRMED MATCH)
0xc1ed2c9c exec1_pa_pegasus_technical (CONFIRMED MATCH)
0x623b9687 exec1_pa_pegasus_marshall (CONFIRMED MATCH)
0x7820766d exec1_pa_pegasus_annihilator (CONFIRMED MATCH)
0x779b6cd5 exec1_pa_pegasus_buzzard (CONFIRMED MATCH)
0xe88a7d5e exec1_pa_pegasus_frogger (CONFIRMED MATCH)
0x45fca6c0 exec1_pa_pegasus_turreted_limo (CONFIRMED MATCH)
0x3f8e4df1 exec1_pa_pegasus_supervolito (CONFIRMED MATCH)
0xec5e03b2 exec1_pa_pegasus_swift_deluxe (CONFIRMED MATCH)
0x6ee59cdc exec1_pa_pegasus_brickade (CONFIRMED MATCH)
0x791fb581 exec1_pa_pegasus_savage (CONFIRMED MATCH)
0x2392588f exec_buy_disable_rumpo3 (CONFIRMED MATCH)
0x56680542 luxe2_the_ballas_knuckle_duster (CONFIRMED MATCH)
0xf5adf343 luxe2_the_pimp_knuckle_duster (CONFIRMED MATCH)
0x3de4aba4 luxe2_the_hustler_knuckle_duster (CONFIRMED MATCH)
0x6853e25b luxe2_the_rock_knuckle_duster (CONFIRMED MATCH)
0xc0dbd2ed luxe2_the_hater_knuckle_duster (CONFIRMED MATCH)
0x2d8736f9 luxe2_the_lover_knuckle_duster (CONFIRMED MATCH)
0xdff23de9 luxe2_the_player_knuckle_duster (CONFIRMED MATCH)
0x8a3342ec luxe2_the_king_knuckle_duster (CONFIRMED MATCH)
0xa284370f luxe2_the_vagos_knuckle_duster (CONFIRMED MATCH)

-824920269 apartment_female_uppers_black_silk_pyjama_top (MANUAL MATCH / CONFIRMED MATCH)
1710650428 apartment_female_uppers_sn_silk_pyjama_top (MANUAL MATCH / CONFIRMED MATCH)
-1506380254 apartment_female_uppers_perseus_silk_pyjama_top (MANUAL MATCH / CONFIRMED MATCH)
1683286258 apartment_female_uppers_gray_silk_pyjama_top (MANUAL MATCH / CONFIRMED MATCH)
-898404375 apartment_female_uppers_red_silk_pyjama_top (MANUAL MATCH / CONFIRMED MATCH)
126216765 apartment_female_uppers_pink_silk_pyjama_top (MANUAL MATCH / CONFIRMED MATCH)
1851964366 apartment_female_uppers_white_silk_pyjama_top (MANUAL MATCH / CONFIRMED MATCH)
202807229 halloween_2015_halloween_loop_1 (MANUAL MATCH / CONFIRMED MATCH)
-795238204 halloween_2015_halloween_loop_2 (MANUAL MATCH / CONFIRMED MATCH)
267984347 halloween_2015_bloody_vampire_bobblehead (MANUAL MATCH / CONFIRMED MATCH)
275702167 car_mods_horn_sad_trombone (MANUAL MATCH / CONFIRMED MATCH)

(These 2 might be a very rare collision but most likely is just a spelling mistake by r*)
1746078541 LUXE2_MALE_UPPERS_BROWN_P_WI_NG_SWEATER  (MANUAL MATCH / CONFIRMED MATCH)
-1748895312 LUXE2_FEMALE_UPPERS_BROWN_P_WI_NG_SWEATER  (MANUAL MATCH / CONFIRMED MATCH)

These hashes start with exec1_pa_pegasus_
0x14d09d7d
0xfc15f181
0x9ab36235
0x8136c418
and end with a vehicle name, my list didn't catch them

**Comment by Wildbrick142** [comment]
thank you! i'll add them shortly.

as for the hashes:
0x14d09d7d = exec1_pa_pegasus_swift_flying_bravo
0xfc15f181 = exec1_pa_pegasus_supervolito_carbon
0x9ab36235 = exec1_pa_pegasus_cargobob_jetsam
0x8136c418 = exec1_pa_pegasus_insurgent_pick_up
