### ISSUE TITLE
not much but some stuff i found

### ISSUE THREAD

**Issue by yasmasdas** [Wildbrick142/V-Tunable-Names#5]
gr_moc_liveries_stars_and_stripes_price
gr_moc_liveries_eagle_claw_price
gr_moc_liveries_eagle_claw_flag_price
gr_moc_liveries_fighting_freedom_price
bikeroutfit1
bikeroutfit2
bikeroutfit3
bikeroutfit4
bikeroutfit5
bikeroutfit6
bikeroutfit8
bikeroutfit7
bikeroutfit9
bikeroutfit10
vc_casino_chip_free_cooldown (might be collision but i dont think it is)

**Comment by Wildbrick142** [comment]
added. thanks!

i can confirm the last one is not a collision
